


import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mehme
 */
public class UrunEkleDisplay extends javax.swing.JFrame {

    /**
     * Creates new form UrunEkle
     */
    public UrunEkleDisplay() {
        initComponents();
        show_uruntablo();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

    }

    public ArrayList<Urun> urunList() {
        ArrayList<Urun> urunList = new ArrayList<>();

        PreparedStatement ps;
        ResultSet rs;
        String sqlurun = "select * from urun";

        try {
            ps = DBConnection.getConnection().prepareStatement(sqlurun);
            rs = ps.executeQuery();
            Urun urun;
            while (rs.next()) {
                urun = new Urun(rs.getInt("kategori_id"), rs.getInt("urun_id"), rs.getString("urunadı"), rs.getInt("urunadet"), rs.getInt("alısfiyat"), rs.getInt("satısfiyat"), rs.getString("urunkodu"), rs.getString("yuzeycesit"), rs.getInt("kalınlıkmm"));
                urunList.add(urun);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
        return urunList;

    }

    public void show_uruntablo() {
        ArrayList<Urun> list = urunList();
        DefaultTableModel model = (DefaultTableModel) showUrunTable.getModel();
        Object[] row = new Object[9];
        for (int i = 0; i < list.size(); i++) {

            row[0] = list.get(i).getKategori_id();
            row[1] = list.get(i).getUrun_id();
            row[2] = list.get(i).getUrunadı();
            row[3] = list.get(i).getUrunadet();
            row[4] = list.get(i).getAlısfiyat();
            row[5] = list.get(i).getSatisfiyat();
            row[6] = list.get(i).getUrunkodu();
            row[7] = list.get(i).getYuzeycesit();
            row[8] = list.get(i).getKalınlıkmm();
            model.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kategori_id = new javax.swing.JTextField();
        urun_id = new javax.swing.JTextField();
        urunadı = new javax.swing.JTextField();
        urunadet = new javax.swing.JTextField();
        alısfiyat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        satısfiyat = new javax.swing.JTextField();
        urunkodu = new javax.swing.JTextField();
        yuzeycesit = new javax.swing.JTextField();
        kalınlıkmm = new javax.swing.JTextField();
        urunkaydet = new javax.swing.JButton();
        backurun = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showUrunTable = new javax.swing.JTable();
        urunguncelle = new javax.swing.JButton();
        urunsil = new javax.swing.JButton();
        uruntemizle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 650));

        jLabel1.setText("kategori_id");

        jLabel2.setText("urun_id");

        jLabel3.setText("urunadı");

        jLabel4.setText("urunadet");

        jLabel5.setText("alısfiyat");

        jLabel6.setText("satısfiyat");

        urun_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun_idActionPerformed(evt);
            }
        });

        urunadı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunadıActionPerformed(evt);
            }
        });

        jLabel7.setText("urunkodu");

        jLabel8.setText("yuzeycesit");

        jLabel9.setText("kalınlıkmm");

        kalınlıkmm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kalınlıkmmActionPerformed(evt);
            }
        });

        urunkaydet.setText("Ürün Ekle");
        urunkaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunkaydetActionPerformed(evt);
            }
        });

        backurun.setText("Ana Menü");
        backurun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backurunActionPerformed(evt);
            }
        });

        showUrunTable.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        showUrunTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "kategori_id", "urun_id", "urunadı", "urunadet", "alısfiyat", "satısfiyat", "urunkodul", "yuzeycesit", "kalınlıkmm"
            }
        ));
        showUrunTable.setRowHeight(25);
        showUrunTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showUrunTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(showUrunTable);

        urunguncelle.setText("Güncelle");
        urunguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunguncelleActionPerformed(evt);
            }
        });

        urunsil.setText("Sil");
        urunsil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunsilActionPerformed(evt);
            }
        });

        uruntemizle.setText("Temizle");
        uruntemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uruntemizleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kategori_id)
                            .addComponent(urun_id)
                            .addComponent(urunadı)
                            .addComponent(urunadet)
                            .addComponent(alısfiyat)
                            .addComponent(satısfiyat)
                            .addComponent(urunkodu)
                            .addComponent(yuzeycesit)
                            .addComponent(kalınlıkmm, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(urunkaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(urunsil, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(urunguncelle, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(uruntemizle, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(backurun, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kategori_id, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urun_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urunadı, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urunadet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alısfiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(satısfiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(urunkodu, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yuzeycesit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kalınlıkmm, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(urunkaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(urunsil, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backurun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(urunguncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uruntemizle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1324, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uruntemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uruntemizleActionPerformed
        // TODO add your handling code here:
        kategori_id.setText("");
        urun_id.setText("");
        urunadı.setText("");
        urunadet.setText("");
        alısfiyat.setText("");
        satısfiyat.setText("");
        urunkodu.setText("");
        yuzeycesit.setText("");
        kalınlıkmm.setText("");

    }//GEN-LAST:event_uruntemizleActionPerformed

    private void urunkaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunkaydetActionPerformed
        
        String sqlurunekle = "insert into urun(kategori_id,urun_id,urunadı,urunadet,alısfiyat,satısfiyat,urunkodu,yuzeycesit,kalınlıkmm)values(?,?,?,?,?,?,?,?,?)";

        try {
            PreparedStatement ps = DBConnection.getConnection().prepareStatement(sqlurunekle);
            ps.setInt(1, Integer.parseInt(kategori_id.getText()));
            ps.setInt(2, Integer.parseInt(urun_id.getText()));
            ps.setString(3, urunadı.getText());
            ps.setInt(4, Integer.parseInt(urunadet.getText()));
            ps.setInt(5, Integer.parseInt(alısfiyat.getText()));
            ps.setInt(6, Integer.parseInt(satısfiyat.getText()));
            ps.setString(7, urunkodu.getText());
            ps.setString(8, yuzeycesit.getText());
            ps.setInt(9, Integer.parseInt(kalınlıkmm.getText()));

            ps.execute();
            JOptionPane.showMessageDialog(null, "Ürün Başarıyla Eklendi.");
            UrunEkleDisplay urunekle = new UrunEkleDisplay();
            urunekle.setVisible(true);
            setVisible(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_urunkaydetActionPerformed

    private void kalınlıkmmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kalınlıkmmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kalınlıkmmActionPerformed

    private void urunadıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunadıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urunadıActionPerformed

    private void urun_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urun_idActionPerformed

    private void backurunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backurunActionPerformed
        // TODO add your handling code here:
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backurunActionPerformed

    private void showUrunTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showUrunTableMouseClicked
        // TODO add your handling code here:
        int i = showUrunTable.getSelectedRow();
        TableModel model = showUrunTable.getModel();
        kategori_id.setText(model.getValueAt(i, 0).toString());
        urun_id.setText(model.getValueAt(i, 1).toString());
        urunadı.setText(model.getValueAt(i, 2).toString());
        urunadet.setText(model.getValueAt(i, 3).toString());
        alısfiyat.setText(model.getValueAt(i, 4).toString());
        satısfiyat.setText(model.getValueAt(i, 5).toString());
        urunkodu.setText(model.getValueAt(i, 6).toString());
        yuzeycesit.setText(model.getValueAt(i, 7).toString());
        kalınlıkmm.setText(model.getValueAt(i, 8).toString());

    }//GEN-LAST:event_showUrunTableMouseClicked

    private void urunguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunguncelleActionPerformed
        // TODO add your handling code here:
        
        try {
            int row = showUrunTable.getSelectedRow();
            String valuekategori_id = (showUrunTable.getModel().getValueAt(row, 0).toString());
            String valueurun_id = (showUrunTable.getModel().getValueAt(row, 1).toString());

            String sqlurunguncelle = "update urun set urunadı=?,urunadet=?,alısfiyat=?,satısfiyat=?,urunkodu=?,yuzeycesit=?,kalınlıkmm=? where kategori_id=" + valuekategori_id + "and urun_id=" + valueurun_id;
            PreparedStatement ps = DBConnection.getConnection().prepareStatement(sqlurunguncelle);
            //ps.setInt(1, Integer.parseInt(kategori_id.getText()));
            //ps.setInt(2, Integer.parseInt(urun_id.getText()));
            ps.setString(1, urunadı.getText());
            ps.setInt(2, Integer.parseInt(urunadet.getText()));
            ps.setInt(3, Integer.parseInt(alısfiyat.getText()));
            ps.setInt(4, Integer.parseInt(satısfiyat.getText()));
            ps.setString(5, urunkodu.getText());
            ps.setString(6, yuzeycesit.getText());
            ps.setInt(7, Integer.parseInt(kalınlıkmm.getText()));

            ps.execute();
            JOptionPane.showMessageDialog(null, "Güncelleme Başarıyla Tamamlandı.");
            UrunEkleDisplay urunekle = new UrunEkleDisplay();
            urunekle.setVisible(true);
            setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_urunguncelleActionPerformed

    private void urunsilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunsilActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(null, "Silme işlemi onaylansın mı?", "SİL", JOptionPane.YES_NO_OPTION);
        if (opt == 0) {
            try {
                int row = showUrunTable.getSelectedRow();
                String valueurun_id = (showUrunTable.getModel().getValueAt(row, 1).toString());
                String sqlurunsil = "delete from urun where urun_id=" + valueurun_id;
                PreparedStatement ps = DBConnection.getConnection().prepareStatement(sqlurunsil);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Silme İşlemi Başarılı.");
                UrunEkleDisplay urunekle = new UrunEkleDisplay();
                urunekle.setVisible(true);
                setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_urunsilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrunEkleDisplay.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrunEkleDisplay.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrunEkleDisplay.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrunEkleDisplay.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UrunEkleDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alısfiyat;
    private javax.swing.JButton backurun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kalınlıkmm;
    private javax.swing.JTextField kategori_id;
    private javax.swing.JTextField satısfiyat;
    private javax.swing.JTable showUrunTable;
    private javax.swing.JTextField urun_id;
    private javax.swing.JTextField urunadet;
    private javax.swing.JTextField urunadı;
    private javax.swing.JButton urunguncelle;
    private javax.swing.JButton urunkaydet;
    private javax.swing.JTextField urunkodu;
    private javax.swing.JButton urunsil;
    private javax.swing.JButton uruntemizle;
    private javax.swing.JTextField yuzeycesit;
    // End of variables declaration//GEN-END:variables
}
